const GAME_DB = [
  { id: 1, game: "Clair Obscur: Expedition 33", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9s5m.jpg", youtubeId: "9R78gS3912c", startSeconds: 20, pop: 10, year: 2025 },
  { id: 2, game: "Cyberpunk 2077", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4hna.jpg", youtubeId: "EegPbRtmzXY", startSeconds: 20, pop: 10, year: 2020 },
  { id: 3, game: "DOOM (2016)", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rs0.jpg", youtubeId: "QHRuTYtSbJQ", startSeconds: 120, pop: 10, year: 2016 },
  { id: 4, game: "Elden Ring", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg", youtubeId: "xTuvLxY6Lrs", startSeconds: 20, pop: 10, year: 2022 },
  { id: 5, game: "Final Fantasy VII", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rcm.jpg", youtubeId: "IYMTzLxGv3M", startSeconds: 120, pop: 10, year: 1997 },
  { id: 6, game: "God of War (2018)", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tmu.jpg", youtubeId: "6nEBkM6NnbI", startSeconds: 20, pop: 10, year: 2018 },
  { id: 7, game: "Grand Theft Auto V", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lbd.jpg", youtubeId: "Ibaze-ZF3Vk", startSeconds: 5, pop: 10, year: 2013 },
  { id: 8, game: "Minecraft", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co49x5.jpg", youtubeId: "5w3rRFWzjcM", startSeconds: 15, pop: 10, year: 2011 },
  { id: 9, game: "Persona 5", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r76.jpg", youtubeId: "ZNGqBDRJgvo", startSeconds: 20, pop: 10, year: 2016 },
  { id: 10, game: "Red Dead Redemption 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg", youtubeId: "HjYLY3BGDY4", startSeconds: 20, pop: 10, year: 2018 },
  { id: 11, game: "Sonic the Hedgehog", youtubeId: "G-i8HYi1QH0", startSeconds: 5, pop: 10, year: 1991 },
  { id: 12, game: "Super Mario Bros.", youtubeId: "uhscMsBhNhw", startSeconds: 5, pop: 10, year: 1985 },
  { id: 13, game: "Super Mario Galaxy", youtubeId: "1bvDHAUv2ak", startSeconds: 5, pop: 10, year: 2007 },
  { id: 14, game: "Tetris", youtubeId: "Bm-WZAK5ltY", startSeconds: 0, pop: 10, year: 1989 },
  { id: 15, game: "The Elder Scrolls V: Skyrim", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rcb.jpg", youtubeId: "813-3iL5OsE", startSeconds: 45, pop: 10, year: 2011 },
  { id: 16, game: "The Last of Us", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7b.jpg", youtubeId: "Y2UOwvUQ8L0", startSeconds: 5, pop: 10, year: 2013 },
  { id: 17, game: "The Last of Us Part II", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3p2d.jpg", youtubeId: "X4qQrGs9_KQ", startSeconds: 5, pop: 10, year: 2020 },
  { id: 18, game: "The Legend of Zelda: Ocarina of Time", youtubeId: "0hEYvdMoF2g", startSeconds: 6, pop: 10, year: 1998 },
  { id: 19, game: "The Witcher 3: Wild Hunt", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg", youtubeId: "uqp4Jc-XkCw", startSeconds: 20, pop: 10, year: 2015 },
  { id: 20, game: "Baldur's Gate 3", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6li9.jpg", youtubeId: "0EwhdbYnHbg", startSeconds: 20, pop: 9, year: 2023 },
  { id: 21, game: "BioShock Infinite", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rce.jpg", youtubeId: "9F1l6xXLSI0", startSeconds: 0, pop: 9, year: 2013 },
  { id: 22, game: "Bloodborne", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tiu.jpg", youtubeId: "ICSk8-pJkX8", startSeconds: 0, pop: 9, year: 2015 },
  { id: 23, game: "DOOM Eternal", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2aoj.jpg", youtubeId: "kpnW68Q8ltc", startSeconds: 30, pop: 9, year: 2020 },
  { id: 24, game: "Dark Souls", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x7d.jpg", youtubeId: "16frInvrJLI", startSeconds: 5, pop: 9, year: 2011 },
  { id: 25, game: "Final Fantasy VI", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rck.jpg", youtubeId: "OhEck7aB-Qc", startSeconds: 60, pop: 9, year: 1994 },
  { id: 26, game: "Final Fantasy X", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rcn.jpg", youtubeId: "6fp81GzKarQ", startSeconds: 0, pop: 9, year: 2001 },
  { id: 27, game: "Ghost of Tsushima", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3bx8.jpg", youtubeId: "XAtBtYbNNGw", startSeconds: 5, pop: 9, year: 2020 },
  { id: 28, game: "Hades", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3glt.jpg", youtubeId: "1nnqzy9_K3I", startSeconds: 0, pop: 9, year: 2020 },
  { id: 29, game: "Halo 2", youtubeId: "Wly8IcmKqvQ", startSeconds: 5, pop: 9, year: 2004 },
  { id: 30, game: "Halo 3", youtubeId: "tdASgfb8RHg", startSeconds: 0, pop: 9, year: 2007 },
  { id: 31, game: "Hollow Knight", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rqh.jpg", youtubeId: "Lp5M2BAXwSo", startSeconds: 15, pop: 9, year: 2017 },
  { id: 32, game: "Horizon Zero Dawn", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tg7.jpg", youtubeId: "_w9B7uwLZeI", startSeconds: 0, pop: 9, year: 2017 },
  { id: 33, game: "Marvel's Spider-Man", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7e.jpg", youtubeId: "sKydT7MMsSo", startSeconds: 0, pop: 9, year: 2018 },
  { id: 34, game: "Mass Effect", youtubeId: "Hqa8l8E-y_c", startSeconds: 0, pop: 9, year: 2007 },
  { id: 35, game: "Mass Effect 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rcj.jpg", youtubeId: "VTsD2FjmLsw", startSeconds: 0, pop: 9, year: 2010 },
  { id: 36, game: "Metal Gear Solid", youtubeId: "f8zsaw6yIzE", startSeconds: 8, pop: 9, year: 1998 },
  { id: 37, game: "Metroid Prime", youtubeId: "ZbbUv1hz6mE", startSeconds: 0, pop: 9, year: 2002 },
  { id: 38, game: "Mortal Kombat", youtubeId: "EAwWPadFsOA", startSeconds: 20, pop: 9, year: 1992 },
  { id: 39, game: "NieR: Automata", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r6r.jpg", youtubeId: "ToBQY630PZE", startSeconds: 30, pop: 9, year: 2017 },
  { id: 40, game: "Pokémon Red/Blue", youtubeId: "s8J65gaJ60k", startSeconds: 10, pop: 9, year: 1996 },
  { id: 41, game: "Portal 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rda.jpg", youtubeId: "ao7GG8FXWqQ", startSeconds: 0, pop: 9, year: 2011 },
  { id: 42, game: "Red Dead Redemption", youtubeId: "Uu8eMDmmaas", startSeconds: 0, pop: 9, year: 2010 },
  { id: 43, game: "Street Fighter II", youtubeId: "Iof5pRAIZmw", startSeconds: 8, pop: 9, year: 1991 },
  { id: 44, game: "Super Mario 64", youtubeId: "Zqa2mgjbOIM", startSeconds: 0, pop: 9, year: 1996 },
  { id: 45, game: "Super Mario Odyssey", youtubeId: "e9r5hx47kxM", startSeconds: 0, pop: 9, year: 2017 },
  { id: 46, game: "Super Smash Bros. Melee", youtubeId: "RxgfG5lftK4", startSeconds: 8, pop: 9, year: 2001 },
  { id: 47, game: "The Legend of Zelda", youtubeId: "cGufy1PAeTU", startSeconds: 10, pop: 9, year: 1986 },
  { id: 48, game: "The Legend of Zelda: Breath of the Wild", youtubeId: "o46NJtHcNgU", startSeconds: 90, pop: 9, year: 2017 },
  { id: 49, game: "The Legend of Zelda: Tears of the Kingdom", youtubeId: "V8RkqQ8fQs4", startSeconds: 45, pop: 9, year: 2023 },
  { id: 50, game: "Undertale", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1ncw.jpg", youtubeId: "0FCvzsVlXpQ", startSeconds: 0, pop: 9, year: 2015 },
  { id: 51, game: "World of Warcraft", youtubeId: "eE5oaOOwInE", startSeconds: 40, pop: 9, year: 2004 },
  { id: 52, game: "Age of Empires II", youtubeId: "2uUHZFta0RM", startSeconds: 0, pop: 8, year: 1999 },
  { id: 53, game: "Alan Wake 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7ahy.jpg", youtubeId: "uxs_HYw_mLk", startSeconds: 0, pop: 8, year: 2023 },
  { id: 54, game: "Assassin's Creed II", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rcg.jpg", youtubeId: "FSVHx23ByhM", startSeconds: 0, pop: 8, year: 2009 },
  { id: 55, game: "Astro Bot", youtubeId: "FAgQsof5fwg", startSeconds: 0, pop: 8, year: 2024 },
  { id: 56, game: "Batman: Arkham City", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1nds.jpg", youtubeId: "SXKrsJZWqK0", startSeconds: 0, pop: 8, year: 2011 },
  { id: 57, game: "Castlevania", youtubeId: "iWMN91gMD_4", startSeconds: 10, pop: 8, year: 1986 },
  { id: 58, game: "Castlevania: Symphony of the Night", youtubeId: "pJsCLe0-KZE", startSeconds: 60, pop: 8, year: 1997 },
  { id: 59, game: "Celeste", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1nfu.jpg", youtubeId: "1rwAvUvvQzQ", startSeconds: 0, pop: 8, year: 2018 },
  { id: 60, game: "Chrono Trigger", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1sbg.jpg", youtubeId: "BXo3DrXHY8w", startSeconds: 0, pop: 8, year: 1995 },
  { id: 61, game: "Civilization IV", youtubeId: "5eB9ybe5y6M", startSeconds: 10, pop: 8, year: 2005 },
  { id: 62, game: "Civilization VI", youtubeId: "WQYN2P3E06s", startSeconds: 55, pop: 8, year: 2016 },
  { id: 63, game: "Crash Bandicoot", youtubeId: "4i8qAZOu5-g", startSeconds: 5, pop: 8, year: 1996 },
  { id: 64, game: "Dark Souls III", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x7g.jpg", youtubeId: "ch6I15iBliE", startSeconds: 0, pop: 8, year: 2016 },
  { id: 65, game: "Death Stranding", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x78.jpg", youtubeId: "wlGdH9XCrgk", startSeconds: 0, pop: 8, year: 2019 },
  { id: 66, game: "Diablo", youtubeId: "Q2evIg-aYw8", startSeconds: 20, pop: 8, year: 1996 },
  { id: 67, game: "Donkey Kong Country", youtubeId: "Al1InhnZUe0", startSeconds: 30, pop: 8, year: 1994 },
  { id: 68, game: "Final Fantasy VII Rebirth", youtubeId: "N8ZyP-AsVeA", startSeconds: 20, pop: 8, year: 2024 },
  { id: 69, game: "Final Fantasy XIV: Endwalker", youtubeId: "FtuwltmTp9I", startSeconds: 45, pop: 8, year: 2021 },
  { id: 70, game: "Final Fantasy XV", youtubeId: "juVZ0TN_2EA", startSeconds: 0, pop: 8, year: 2016 },
  { id: 71, game: "Final Fantasy XVI", youtubeId: "-3JbbFL-aks", startSeconds: 30, pop: 8, year: 2023 },
  { id: 72, game: "Fire Emblem: Three Houses", youtubeId: "d59m-yVtiSg", startSeconds: 20, pop: 8, year: 2019 },
  { id: 73, game: "GoldenEye 007", youtubeId: "A7lLHJ6yfH0", startSeconds: 5, pop: 8, year: 1997 },
  { id: 74, game: "Hades II", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8kvp.jpg", youtubeId: "N7QSavYWEE0", startSeconds: 10, pop: 8, year: 2025 },
  { id: 75, game: "Hi-Fi Rush", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5w6c.jpg", youtubeId: "a2BUEzdjfpY", startSeconds: 30, pop: 8, year: 2023 },
  { id: 76, game: "Kingdom Hearts", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1ri8.jpg", youtubeId: "Jk4P10nsq4c", startSeconds: 20, pop: 8, year: 2002 },
  { id: 77, game: "Mario Kart 8", youtubeId: "NA6CAgv6p6g", startSeconds: 15, pop: 8, year: 2014 },
  { id: 78, game: "Mega Man X", youtubeId: "APNQghAQlzM", startSeconds: 8, pop: 8, year: 1993 },
  { id: 79, game: "Persona 4 Golden", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r77.jpg", youtubeId: "7H5pYCw4ET4", startSeconds: 35, pop: 8, year: 2012 },
  { id: 80, game: "Phoenix Wright: Ace Attorney", youtubeId: "UFcJmOs8DRQ", startSeconds: 12, pop: 8, year: 2001 },
  { id: 81, game: "Sonic Adventure", youtubeId: "uEzXFuYN89k", startSeconds: 30, pop: 8, year: 1998 },
  { id: 82, game: "Splatoon", youtubeId: "LBQmvJyIKTg", startSeconds: 20, pop: 8, year: 2015 },
  { id: 83, game: "StarCraft", youtubeId: "mD4GbGmvNRc", startSeconds: 10, pop: 8, year: 1998 },
  { id: 84, game: "Super Metroid", youtubeId: "WVTzg2kvNaQ", startSeconds: 5, pop: 8, year: 1994 },
  { id: 85, game: "The Legend of Zelda: A Link to the Past", youtubeId: "bK-ttWxl4CI", startSeconds: 8, pop: 8, year: 1991 },
  { id: 86, game: "The Legend of Zelda: Majora's Mask", youtubeId: "vbMQfaG6lo8", startSeconds: 30, pop: 8, year: 2000 },
  { id: 87, game: "Ace Combat 04: Shattered Skies", youtubeId: "lYW1F7v6D-Q", startSeconds: 40, pop: 7, year: 2001 },
  { id: 88, game: "Donkey Kong Country 2", youtubeId: "goKKrHTlWhw", startSeconds: 60, pop: 7, year: 1995 },
  { id: 89, game: "Grim Fandango", youtubeId: "X6ymVaq3Fqk", startSeconds: 20, pop: 7, year: 1998 },
  { id: 90, game: "Guilty Gear -Strive-", youtubeId: "ikQHkhL8YMM", startSeconds: 35, pop: 7, year: 2021 },
  { id: 91, game: "Octopath Traveler", youtubeId: "b7Zc3f8cPnU", startSeconds: 35, pop: 7, year: 2018 },
  { id: 92, game: "Professor Layton and the Curious Village", youtubeId: "GYlpoteRT6o", startSeconds: 15, pop: 7, year: 2007 },
  { id: 93, game: "Transistor", youtubeId: "f9O2Rjn1azc", startSeconds: 45, pop: 7, year: 2014 },
  { id: 94, game: "Xenoblade Chronicles 2", youtubeId: "Tx3AbguQZHU", startSeconds: 50, pop: 7, year: 2017 },
  { id: 95, game: "Kirby's Epic Yarn", youtubeId: "akSzw8A5vxc", startSeconds: 30, pop: 6, year: 2010 },
  { id: 96, game: "Lufia II: Rise of the Sinistrals", youtubeId: "RBnYGYa6l3M", startSeconds: 20, pop: 6, year: 1995 },
  { id: 97, game: "Myst", youtubeId: "9zCevFE0fMs", startSeconds: 20, pop: 6, year: 1993 },
  { id: 98, game: "Shin Megami Tensei III: Nocturne", youtubeId: "qDsDYCI3fyc", startSeconds: 15, pop: 6, year: 2003 },
  { id: 99, game: "SimCity 3000", youtubeId: "O42kxeilMaQ", startSeconds: 20, pop: 6, year: 1999 },
  { id: 100, game: "Tunic", youtubeId: "nnvjKf_mRYM", startSeconds: 30, pop: 6, year: 2022 },
];

function getPopBand(pop) {
  if (pop >= 9) return 'high';
  if (pop >= 7) return 'mid';
  return 'low';
}
