const GAME_DB = [
  { id: 1, game: "Clair Obscur: Expedition 33", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9gam.jpg", youtubeId: "zmvsw2ILX5k", startSeconds: 29, pop: 10, year: 2025 },
  { id: 2, game: "Cyberpunk 2077", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2mjs.jpg", youtubeId: "EegPbRtmzXY", startSeconds: 51, pop: 10, year: 2020 },
  { id: 3, game: "DOOM (2016)", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1nc7.jpg", youtubeId: "zZMg9ryeWOw", startSeconds: 107, pop: 10, year: 2016 },
  { id: 4, game: "Elden Ring", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg", youtubeId: "xTuvLxY6Lrs", startSeconds: 18, pop: 10, year: 2022 },
  { id: 5, game: "Final Fantasy VII", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2kx2.jpg", youtubeId: "IYMTzLxGv3M", startSeconds: 118, pop: 10, year: 1997 },
  { id: 6, game: "God of War (2018)", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tmu.jpg", youtubeId: "jpyVfd8TyoI", startSeconds: 75, pop: 10, year: 2018 },
  { id: 7, game: "Grand Theft Auto V", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lbd.jpg", youtubeId: "Ibaze-ZF3Vk", startSeconds: 29, pop: 10, year: 2013 },
  { id: 8, game: "Minecraft", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co49x5.jpg", youtubeId: "5w3rRFWzjcM", startSeconds: 15, pop: 10, year: 2011 },
  { id: 9, game: "Persona 5", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r76.jpg", youtubeId: "ZNGqBDRJgvo", startSeconds: 46, pop: 10, year: 2016 },
  { id: 10, game: "Red Dead Redemption 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg", youtubeId: "AF22vaGLziM", startSeconds: 28, pop: 10, year: 2018 },
  { id: 11, game: "Sonic the Hedgehog", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co63oc.jpg", youtubeId: "G-i8HYi1QH0", startSeconds: 1, pop: 10, year: 1991 },
  { id: 12, game: "Super Mario Bros.", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6pib.webp", youtubeId: "uhscMsBhNhw", startSeconds: 17, pop: 10, year: 1985 },
  { id: 13, game: "Super Mario Galaxy", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co21ro.webp", youtubeId: "1bvDHAUv2ak", startSeconds: 11, pop: 10, year: 2007 },
  { id: 14, game: "Tetris", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6o1v.webp", youtubeId: "Bm-WZAK5ltY", startSeconds: 0, pop: 10, year: 1989 },
  { id: 15, game: "The Elder Scrolls V: Skyrim", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cobt0i.webp", youtubeId: "813-3iL5OsE", startSeconds: 29, pop: 10, year: 2011 },
  { id: 16, game: "The Last of Us", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7f.jpg", youtubeId: "Y2UOwvUQ8L0", startSeconds: 19, pop: 10, year: 2013 },
  { id: 17, game: "The Last of Us Part II", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5ziw.webp", youtubeId: "fAdpMMNeiuM", startSeconds: 58, pop: 10, year: 2020 },
  { id: 18, game: "The Legend of Zelda: Ocarina of Time", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3nnx.webp", youtubeId: "0hEYvdMoF2g", startSeconds: 22, pop: 10, year: 1998 },
  { id: 19, game: "The Witcher 3: Wild Hunt", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg", youtubeId: "i1qjKo6Ts60", startSeconds: 93, pop: 10, year: 2015 },
  { id: 20, game: "Baldur's Gate 3", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co670h.webp", youtubeId: "0EwhdbYnHbg", startSeconds: 40, pop: 9, year: 2023 },
  { id: 21, game: "BioShock Infinite", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2n12.jpg", youtubeId: "9F1l6xXLSI0", startSeconds: 71, pop: 9, year: 2013 },
  { id: 22, game: "Bloodborne", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob99l.webp", youtubeId: "ICSk8-pJkX8", startSeconds: 62, pop: 9, year: 2015 },
  { id: 23, game: "DOOM Eternal", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3p5n.webp", youtubeId: "kpnW68Q8ltc", startSeconds: 65, pop: 9, year: 2020 },
  { id: 24, game: "Dark Souls", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x78.webp", youtubeId: "16frInvrJLI", startSeconds: 0, pop: 9, year: 2011 },
  { id: 25, game: "Final Fantasy VI", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8kxj.webp", youtubeId: "jm1a-DwLExU", startSeconds: 160, pop: 9, year: 1994 },
  { id: 26, game: "Final Fantasy X", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tr1.webp", youtubeId: "cxPvGGmWM3A", startSeconds: 0, pop: 9, year: 2001 },
  { id: 27, game: "Ghost of Tsushima", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2crj.webp", youtubeId: "uoqWH32i1wg", startSeconds: 116, pop: 9, year: 2020 },
  { id: 28, game: "Hades", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob9kr.webp", youtubeId: "oksESAMg7WM", startSeconds: 0, pop: 9, year: 2020 },
  { id: 29, game: "Halo 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x77.webp", youtubeId: "Wly8IcmKqvQ", startSeconds: 39, pop: 9, year: 2004 },
  { id: 30, game: "Halo 3", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1xhc.webp", youtubeId: "tdASgfb8RHg", startSeconds: 38, pop: 9, year: 2007 },
  { id: 31, game: "Hollow Knight", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cobfzp.webp", youtubeId: "r6PuACnHkNY", startSeconds: 1, pop: 9, year: 2017 },
  { id: 32, game: "Horizon Zero Dawn", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2una.webp", youtubeId: "obX7W9cLEKk", startSeconds: 58, pop: 9, year: 2017 },
  { id: 33, game: "Marvel's Spider-Man", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r77.jpg", youtubeId: "B_jPNlVeZNQ", startSeconds: 112, pop: 9, year: 2018 },
  { id: 34, game: "Mass Effect", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x7o.webp", youtubeId: "Hqa8l8E-y_c", startSeconds: 8, pop: 9, year: 2007 },
  { id: 35, game: "Mass Effect 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co20ac.webp", youtubeId: "ZQy8dqzV56A", startSeconds: 169, pop: 9, year: 2010 },
  { id: 36, game: "Metal Gear Solid", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cobpak.webp", youtubeId: "f8zsaw6yIzE", startSeconds: 8, pop: 9, year: 1998 },
  { id: 37, game: "Metroid Prime", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3w4w.webp", youtubeId: "15_PGFMJ4E4", startSeconds: 13, pop: 9, year: 2002 },
  { id: 38, game: "Mortal Kombat", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co69x7.webp", youtubeId: "EAwWPadFsOA", startSeconds: 16, pop: 9, year: 1992 },
  { id: 39, game: "NieR: Automata", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5pcj.webp", youtubeId: "LC5HsZt4oNc", startSeconds: 66, pop: 9, year: 2017 },
  { id: 40, game: "Pokémon Red/Blue", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5pi4.webp", youtubeId: "Fupfr_eVLPo", startSeconds: 14, pop: 9, year: 1996 },
  { id: 41, game: "Portal 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rs4.jpg", youtubeId: "dVVZaZ8yO6o", startSeconds: 0, pop: 9, year: 2011 },
  { id: 42, game: "Red Dead Redemption", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lcv.webp", youtubeId: "5-BIqqSe1nU", startSeconds: 129, pop: 9, year: 2010 },
  { id: 43, game: "Street Fighter II", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co55et.webp", youtubeId: "Iof5pRAIZmw", startSeconds: 0, pop: 9, year: 1991 },
  { id: 44, game: "Super Mario 64", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co721v.webp", youtubeId: "pYAjvWCVkH0", startSeconds: 0, pop: 9, year: 1996 },
  { id: 45, game: "Super Mario Odyssey", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1mxf.webp", youtubeId: "e9r5hx47kxM", startSeconds: 0, pop: 9, year: 2017 },
  { id: 46, game: "Super Smash Bros. Melee", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co21yv.webp", youtubeId: "RxgfG5lftK4", startSeconds: 19, pop: 9, year: 2001 },
  { id: 47, game: "The Legend of Zelda", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1uii.webp", youtubeId: "uyMKWJ5e1kg", startSeconds: 26, pop: 9, year: 1986 },
  { id: 48, game: "The Legend of Zelda: Breath of the Wild", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3p2d.webp", youtubeId: "tDkjr_cYO6M", startSeconds: 0, pop: 9, year: 2017 },
  { id: 49, game: "The Legend of Zelda: Tears of the Kingdom", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5vmg.webp", youtubeId: "V8RkqQ8fQs4", startSeconds: 42, pop: 9, year: 2023 },
  { id: 50, game: "Undertale", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob1t2.webp", youtubeId: "0FCvzsVlXpQ", startSeconds: 0, pop: 9, year: 2015 },
  { id: 51, game: "World of Warcraft", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2l7z.webp", youtubeId: "eE5oaOOwInE", startSeconds: 1, pop: 9, year: 2004 },
  { id: 52, game: "Age of Empires II", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co55xo.webp", youtubeId: "Rxbcp2AK-2Y", startSeconds: 0, pop: 8, year: 1999 },
  { id: 53, game: "Alan Wake 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6jar.webp", youtubeId: "uxs_HYw_mLk", startSeconds: 132, pop: 8, year: 2023 },
  { id: 54, game: "Assassin's Creed II", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rcf.webp", youtubeId: "FSVHx23ByhM", startSeconds: 38, pop: 8, year: 2009 },
  { id: 55, game: "Astro Bot", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/coba3k.webp", youtubeId: "FAgQsof5fwg", startSeconds: 0, pop: 8, year: 2024 },
  { id: 56, game: "Batman: Arkham City", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1voh.webp", youtubeId: "SXKrsJZWqK0", startSeconds: 106, pop: 8, year: 2011 },
  { id: 57, game: "Castlevania", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5geb.webp", youtubeId: "btgi3TPL3AE", startSeconds: 22, pop: 8, year: 1986 },
  { id: 58, game: "Castlevania: Symphony of the Night", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co53m8.webp", youtubeId: "ZHMZUflSb0Y", startSeconds: 20, pop: 8, year: 1997 },
  { id: 59, game: "Celeste", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob9dh.webp", youtubeId: "1rwAvUvvQzQ", startSeconds: 0, pop: 8, year: 2018 },
  { id: 60, game: "Chrono Trigger", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co71yh.webp", youtubeId: "-1LDIPBWjtU", startSeconds: 15, pop: 8, year: 1995 },
  { id: 61, game: "Civilization IV", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rjp.webp", youtubeId: "5eB9ybe5y6M", startSeconds: 51, pop: 8, year: 2005 },
  { id: 62, game: "Civilization VI", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/coaaqr.webp", youtubeId: "WQYN2P3E06s", startSeconds: 47, pop: 8, year: 2016 },
  { id: 63, game: "Crash Bandicoot", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co555l.webp", youtubeId: "4i8qAZOu5-g", startSeconds: 3, pop: 8, year: 1996 },
  { id: 64, game: "Dark Souls III", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob9ed.webp", youtubeId: "ch6I15iBliE", startSeconds: 0, pop: 8, year: 2016 },
  { id: 65, game: "Death Stranding", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cobksf.webp", youtubeId: "Ghk1RFr51xo", startSeconds: 6, pop: 8, year: 2019 },
  { id: 66, game: "Diablo", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3ggo.webp", youtubeId: "Q2evIg-aYw8", startSeconds: 0, pop: 8, year: 1996 },
  { id: 67, game: "Donkey Kong Country", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co70qn.webp", youtubeId: "Al1InhnZUe0", startSeconds: 32, pop: 8, year: 1994 },
  { id: 68, game: "Final Fantasy VII Rebirth", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob9k6.webp", youtubeId: "t4fh7wsJpA0", startSeconds: 90, pop: 8, year: 2024 },
  { id: 69, game: "Final Fantasy XIV Online", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cobl9m.webp", youtubeId: "4vR0wo911N0", startSeconds: 11, pop: 8, year: 2021 },
  { id: 70, game: "Final Fantasy XV", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6nz1.webp", youtubeId: "juVZ0TN_2EA", startSeconds: 19, pop: 8, year: 2016 },
  { id: 71, game: "Final Fantasy XVI", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cobd9i.webp", youtubeId: "a925dm5smWU", startSeconds: 23, pop: 8, year: 2023 },
  { id: 72, game: "Fire Emblem: Three Houses", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1n8t.webp", youtubeId: "B6HVV9VXlh8", startSeconds: 64, pop: 8, year: 2019 },
  { id: 73, game: "GoldenEye 007", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/coa0y2.webp", youtubeId: "p1BvOMykITY", startSeconds: 5, pop: 8, year: 1997 },
  { id: 74, game: "Hades II", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/coaknx.webp", youtubeId: "N7QSavYWEE0", startSeconds: 10, pop: 8, year: 2025 },
  { id: 75, game: "Hi-Fi Rush", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6219.webp", youtubeId: "ZENxrHmEhsI", startSeconds: 4, pop: 8, year: 2023 },
  { id: 76, game: "Kingdom Hearts", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co30zf.webp", youtubeId: "Jk4P10nsq4c", startSeconds: 24, pop: 8, year: 2002 },
  { id: 77, game: "Mario Kart 8", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co213q.webp", youtubeId: "M816Wz-5gUM", startSeconds: 9, pop: 8, year: 2014 },
  { id: 78, game: "Mega Man X", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3tu2.webp", youtubeId: "MkhIGJsYb4I", startSeconds: 2, pop: 8, year: 1993 },
  { id: 79, game: "Persona 4 Golden", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1n1x.jpg", youtubeId: "7H5pYCw4ET4", startSeconds: 19, pop: 8, year: 2012 },
  { id: 80, game: "Phoenix Wright: Ace Attorney", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5z8s.webp", youtubeId: "UFcJmOs8DRQ", startSeconds: 6, pop: 8, year: 2001 },
  { id: 81, game: "Sonic Adventure", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5jac.webp", youtubeId: "uEzXFuYN89k", startSeconds: 30, pop: 8, year: 1998 },
  { id: 82, game: "Splatoon", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob8ra.webp", youtubeId: "LBQmvJyIKTg", startSeconds: 11, pop: 8, year: 2015 },
  { id: 83, game: "StarCraft", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9n6m.webp", youtubeId: "mD4GbGmvNRc", startSeconds: 36, pop: 8, year: 1998 },
  { id: 84, game: "Super Metroid", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5osy.webp", youtubeId: "gXIdLLc8s-E", startSeconds: 34, pop: 8, year: 1994 },
  { id: 85, game: "The Legend of Zelda: A Link to the Past", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3vzn.webp", youtubeId: "bK-ttWxl4CI", startSeconds: 6, pop: 8, year: 1991 },
  { id: 86, game: "The Legend of Zelda: Majora's Mask", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3pah.webp", youtubeId: "bNaBpN7LdSY", startSeconds: 31, pop: 8, year: 2000 },
  { id: 87, game: "Ace Combat 04: Shattered Skies", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cobr0u.webp", youtubeId: "lYW1F7v6D-Q", startSeconds: 79, pop: 7, year: 2001 },
  { id: 88, game: "Donkey Kong Country 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7n25.webp", youtubeId: "goKKrHTlWhw", startSeconds: 78, pop: 7, year: 1995 },
  { id: 89, game: "Grim Fandango", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co25r3.webp", youtubeId: "-LcUFq47Kmk", startSeconds: 0, pop: 7, year: 1998 },
  { id: 90, game: "Guilty Gear -Strive-", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lby.webp", youtubeId: "ikQHkhL8YMM", startSeconds: 27, pop: 7, year: 2021 },
  { id: 91, game: "Octopath Traveler", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4kap.webp", youtubeId: "sR1OHW_IReI", startSeconds: 47, pop: 7, year: 2018 },
  { id: 92, game: "Professor Layton and the Curious Village", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob8lr.webp", youtubeId: "GYlpoteRT6o", startSeconds: 22, pop: 7, year: 2007 },
  { id: 93, game: "Transistor", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob23o.webp", youtubeId: "f9O2Rjn1azc", startSeconds: 48, pop: 7, year: 2014 },
  { id: 94, game: "Xenoblade Chronicles 2", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob8r2.webp", youtubeId: "Tx3AbguQZHU", startSeconds: 0, pop: 7, year: 2017 },
  { id: 95, game: "Kirby Super Star", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4qyi.webp", youtubeId: "IRFom8SvKXI", startSeconds: 6, pop: 6, year: 2010 },
  { id: 96, game: "Lufia II: Rise of the Sinistrals", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9mg3.webp", youtubeId: "RBnYGYa6l3M", startSeconds: 0, pop: 6, year: 1995 },
  { id: 97, game: "Myst", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7zx8.webp", youtubeId: "hS3HVYHOSis", startSeconds: 26, pop: 6, year: 1993 },
  { id: 98, game: "Shin Megami Tensei III: Nocturne", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9klt.webp", youtubeId: "leRmgnAG5dw", startSeconds: 9, pop: 6, year: 2003 },
  { id: 99, game: "SimCity 3000", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1o4e.webp", youtubeId: "vBszCIKYumk", startSeconds: 22, pop: 6, year: 1999 },
  { id: 100, game: "Tunic", cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/td1t8kb33gyo8mvhl2pc.webp", youtubeId: "nnvjKf_mRYM", startSeconds: 30, pop: 6, year: 2022 },
];
